[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn server:app --bind 0.0.0.0:8080 --timeout 600 --workers 1 --graceful-timeout 600 --keep-alive 5"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
